/** Whisper's supported languages, most-used first then alphabetical. */
export const LANGUAGES: { code: string; name: string; native: string }[] = [
  { code: 'en', name: 'English',              native: '' },
  { code: 'es', name: 'Spanish',              native: 'Español' },
  { code: 'fr', name: 'French',               native: 'Français' },
  { code: 'de', name: 'German',               native: 'Deutsch' },
  { code: 'pt', name: 'Portuguese',           native: 'Português' },
  { code: 'it', name: 'Italian',              native: 'Italiano' },
  { code: 'nl', name: 'Dutch',                native: 'Nederlands' },
  { code: 'zh', name: 'Chinese',              native: '中文' },
  { code: 'ja', name: 'Japanese',             native: '日本語' },
  { code: 'ko', name: 'Korean',               native: '한국어' },
  { code: 'ru', name: 'Russian',              native: 'Русский' },
  { code: 'ar', name: 'Arabic',               native: 'العربية' },
  { code: 'hi', name: 'Hindi',                native: 'हिन्दी' },
  { code: 'tr', name: 'Turkish',              native: 'Türkçe' },
  { code: 'pl', name: 'Polish',               native: 'Polski' },
  { code: 'sv', name: 'Swedish',              native: 'Svenska' },
  { code: 'da', name: 'Danish',               native: 'Dansk' },
  { code: 'no', name: 'Norwegian',            native: 'Norsk' },
  { code: 'fi', name: 'Finnish',              native: 'Suomi' },
  { code: 'cs', name: 'Czech',                native: 'Čeština' },
  { code: 'el', name: 'Greek',                native: 'Ελληνικά' },
  { code: 'he', name: 'Hebrew',               native: 'עברית' },
  { code: 'hu', name: 'Hungarian',            native: 'Magyar' },
  { code: 'id', name: 'Indonesian',           native: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay',                native: 'Bahasa Melayu' },
  { code: 'ro', name: 'Romanian',             native: 'Română' },
  { code: 'sk', name: 'Slovak',               native: 'Slovenčina' },
  { code: 'th', name: 'Thai',                 native: 'ไทย' },
  { code: 'uk', name: 'Ukrainian',            native: 'Українська' },
  { code: 'vi', name: 'Vietnamese',           native: 'Tiếng Việt' },
  { code: 'ca', name: 'Catalan',              native: 'Català' },
  { code: 'bg', name: 'Bulgarian',            native: 'Български' },
  { code: 'hr', name: 'Croatian',             native: 'Hrvatski' },
  { code: 'lt', name: 'Lithuanian',           native: 'Lietuvių' },
  { code: 'lv', name: 'Latvian',              native: 'Latviešu' },
  { code: 'et', name: 'Estonian',             native: 'Eesti' },
  { code: 'sl', name: 'Slovenian',            native: 'Slovenščina' },
  { code: 'fa', name: 'Persian',              native: 'فارسی' },
  { code: 'ta', name: 'Tamil',                native: 'தமிழ்' },
  { code: 'ur', name: 'Urdu',                 native: 'اردو' }
]
